default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: memmermolano_development

test:
  <<: *default
  database: memmermolano_test

production:
  <<: *default
  host: db
  database: memmermolano
  password: <%= ENV['DB_PASSWORD'] %>
